server:
  port: 8083
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]' :
           allowedOrigins: "*"
           allowedHeaders:
             - x-requested-with
             - authorization
             - content-type
             - credential
           allowedMethods:
             - POST
             - GET
             - PUT
             - DELETE
             - OPTIONS
      routes:
        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/api/v1/members/**
        - id: unentered
          uri: lb://UNENTERED
          predicates:
            - Path=/api/v1/unentered/**
        - id: notification
          uri: lb://NOTIFICATION
          predicates:
            - Path=/api/v1/notification/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true