server:
  port : 8080

spring:
  application:
    name: member
  datasource:
    username: 'seok'
    password: '1234'
    url: jdbc:postgresql://localhost:5432/member
  jpa:
    properties:
      hibernate :
        dialect : org.hibernate.dialect.PostgreSQLDialect
        format_sql : true
    hibernate:
      ddl-auto: 'create-drop'
    show-sql : true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: FULL

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true