server:
  port: 8084

spring:
  application:
    name: batch
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/batch
    username: 'seok'
    password: '1234'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
