spring:
  application:
    name: unentered
  datasource:
    username: 'seok'
    password: '1234'
    url: jdbc:postgres://localhost:5435/unentered
  jpa:
    show-sql : true
    properties:
      hibernate : org.hibernate.dialect.PostgreSQLDialect
      format_sql : true
    hibernate:
      ddl-auto: 'create-drop'
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true