server:
  port: 8081

spring:
  application:
    name: unentered
  datasource:
    username: 'seok'
    password: '1234'
    url: jdbc:postgresql://localhost:5432/unentered
  jpa:
    show-sql: true
    properties:
      hibernate :
        dialect : org.hibernate.dialect.PostgreSQLDialect
        format_sql : true
    hibernate:
      ddl-auto: 'create-drop'
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true